name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t harshhatade/ride-ai-app:latest .

      - name: Push to Docker Hub
        run: docker push harshhatade/ride-ai-app:latest
        
      - name: Trigger Render Deploy
        run: curl -X POST "https://api.render.com/deploy/srv-d6hcsnlm5p6s73bh7asg?key=XkY-_1D0MQI"
